title: SAMPINDO Status
buildFuture: true
defaultContentLanguage: en
languageCode: id
baseURL: https://Incident.sampindo.com
params:
  disableDarkMode: true
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Indonesia Roleplay
      category: SA-MP
    - name: Javanese Roleplay
      category: SA-MP
    - name: Website
      description: ""
      category: CORE
    - name: Forum
      description: ""
      category: CORE
    - name: Monitor
      category: CORE
    - name: Status
      category: CORE
    - name: Radio
      category: CORE
    - name: API
      category: CORE
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: CORE
      description: The core of servers are located here.
      closed: false
      untitled: false
    - name: SA-MP
      description: Indonesia Roleplay Status
      closed: false
    - name: MTA SA
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
